### ISSUE TITLE
Relative context URI's

### ISSUE THREAD

**Issue by hsolbrig** [fhircat/fhir_to_jsonld_context#4]
Once the JSON-LD Playground gets fixed, context URI's should be changed to relative URI's.  This will make Issue #1 moot

**Comment by hsolbrig** [comment]
As an example, Account.context.jsonld should read:
```json
{
  "@context": {
    "@version": 1.1,
    "@vocab": "http://example.com/UNKNOWN#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "fhir": "http://hl7.org/fhir/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "resourceType": {
      "@id": "rdf:type",
      "@type": "@id"
    },
    "id": {
      "@id": "fhir:Resource.id",
      "@context": "string.context.jsonld"
    },
```

The server URL (https://fhircat.org/...) should never appear in a context.

**Comment by jiaola** [comment]
Fixed. See https://fhircat.org/fhir/contexts/r5/account.context.jsonld as an example

**Comment by hsolbrig** [comment]
Quick test:  http://tinyurl.com/yfxx4hjm
